/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schedule_management;



import arraylist_handler.ArrayListHandler;
import javax.swing.JDialog;
import javax.swing.JLabel;
import main.vsa_dashboard;

/**
 *
 * @author jdev1
 */
public class Schedule_Management extends javax.swing.JFrame {

    /**
     * Creates new form Schedule_Management
     */
    
    public Schedule_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schedule_managementTitle = new javax.swing.JLabel();
        back_to_dashbaord = new javax.swing.JButton();
        edit_schedule = new javax.swing.JButton();
        create_schedule = new javax.swing.JButton();
        delete_schedule = new javax.swing.JButton();
        display_schedule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        schedule_managementTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        schedule_managementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schedule_managementTitle.setText("Schedule Management");

        back_to_dashbaord.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        back_to_dashbaord.setText("Back To Dashboard");
        back_to_dashbaord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_dashbaordMouseClicked(evt);
            }
        });

        edit_schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit_schedule.setText("Edit Schedule");
        edit_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_scheduleMouseClicked(evt);
            }
        });

        create_schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        create_schedule.setText("Create Schedule");
        create_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_scheduleMouseClicked(evt);
            }
        });
        create_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_scheduleActionPerformed(evt);
            }
        });

        delete_schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete_schedule.setText("Delete Schedule");
        delete_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_scheduleMouseClicked(evt);
            }
        });

        display_schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        display_schedule.setText("Display Schedule");
        display_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_scheduleMouseClicked(evt);
            }
        });
        display_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_scheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(schedule_managementTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back_to_dashbaord)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(display_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(create_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(schedule_managementTitle)
                .addGap(51, 51, 51)
                .addComponent(edit_schedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display_schedule)
                .addGap(8, 8, 8)
                .addComponent(delete_schedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(back_to_dashbaord))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(create_schedule)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_to_dashbaordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_dashbaordMouseClicked
        // TODO add your handling code here:
        
        vsa_dashboard dash = new vsa_dashboard();
        this.setVisible(false);
        dash.setVisible(true);
    }//GEN-LAST:event_back_to_dashbaordMouseClicked

    private void display_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_scheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display_scheduleActionPerformed

    private void create_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_scheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_scheduleActionPerformed

    private void create_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_scheduleMouseClicked
        // TODO add your handling code here:
        Task_Schedule create_schedule = new Task_Schedule ();
        this.setVisible(false);
        create_schedule.setVisible(true);
    }//GEN-LAST:event_create_scheduleMouseClicked

    private void delete_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_scheduleMouseClicked
        // TODO add your handling code here:
        ArrayListHandler.deleteSchedule();
        JDialog dialog = new JDialog(this, "Schedule Deletion Confirmation");
                dialog.add(new JLabel("Your schedule has been deleted."));
                dialog.setSize(250, 100);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);
                dialog.setResizable(false);
        
    }//GEN-LAST:event_delete_scheduleMouseClicked

    private void edit_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_scheduleMouseClicked
        // TODO add your handling code here:
        Edit_Schedule create_schedule = new Edit_Schedule ();
        this.setVisible(false);
        create_schedule.setVisible(true);
    }//GEN-LAST:event_edit_scheduleMouseClicked

    private void display_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_scheduleMouseClicked
        // TODO add your handling code here:
        Display_Schedule display_schedule = new Display_Schedule ();
        this.setVisible(false);
        display_schedule.setVisible(true);
        
    }//GEN-LAST:event_display_scheduleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_dashbaord;
    private javax.swing.JButton create_schedule;
    private javax.swing.JButton delete_schedule;
    private javax.swing.JButton display_schedule;
    private javax.swing.JButton edit_schedule;
    private javax.swing.JLabel schedule_managementTitle;
    // End of variables declaration//GEN-END:variables
}
